-- =============================================================
-- Student Attendance & Registration System
-- File: 02_sequences.sql
-- Auto-increment sequences for all PK columns
-- =============================================================

-- Drop existing sequences if re-running
BEGIN
  FOR s IN (
    SELECT sequence_name FROM user_sequences
    WHERE sequence_name IN (
      'SEQ_SESSIONS','SEQ_FACULTY','SEQ_COURSES','SEQ_STUDENTS',
      'SEQ_COURSE_INSTANCES','SEQ_SECTIONS','SEQ_BATCHES',
      'SEQ_REGISTRATIONS','SEQ_ATTENDANCE','SEQ_ADM_DROP_LOG'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

CREATE SEQUENCE SEQ_SESSIONS        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FACULTY         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COURSES         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STUDENTS        START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COURSE_INSTANCES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SECTIONS        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BATCHES         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REGISTRATIONS   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ATTENDANCE      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADM_DROP_LOG    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

PROMPT Sequences created successfully.
