-- Master Sync Script
SET FEEDBACK OFF;
SET VERIFY OFF;

PROMPT [1/8] Schema...
@/tmp/sql/01_schema.sql
PROMPT [2/8] Sequences...
@/tmp/sql/02_sequences.sql
PROMPT [3/8] Types...
@/tmp/sql/03_types.sql
PROMPT [4/8] Triggers...
@/tmp/sql/04_triggers.sql
PROMPT [5/8] Functions...
@/tmp/sql/05_functions.sql
PROMPT [6/8] Registration Pkg...
@/tmp/sql/06_pkg_registration.sql
PROMPT [7/8] Attendance Pkg...
@/tmp/sql/07_pkg_attendance.sql
PROMPT [8/8] Sample Data (100 Students)...
@/tmp/sql/08_sample_data.sql

PROMPT Sync Complete! 🚀
docker exec -it oracle-xe sqlplus system/oracle123@//localhost:1521/XE @/tmp/sql/07_pkg_attendance.sql
EXIT;
